### ISSUE TITLE
Volume Contest Query

### ISSUE THREAD

**Issue by princearoragithub** [jediswaplabs/dashboard-backend#16]
Specs for volume contest:
https://docs.google.com/spreadsheets/d/1P9UNzZnr-kuF-zOTj8MyRaDfmJRkbCbpo_UqS7EraKY/edit#gid=1464182994

We need to write a query for calculating user points. We have all the swaps in mongo db. The query needs to:
1) Fetch all the required swaps for a user (from a particular block or datetime)
2) Calculate the points based on USD volume and pair (stable or not)
3) Add up the scores to give weekly points and total score. The weekly points need to adhere to upper limit of points per week.

**Comment by duxin0817060114** [comment]
That's a good idea.
